# GitHub Pages Configuration
# This tells GitHub Pages how to serve our JAMstack site

# Exclude everything except dist folder contents
exclude:
  - strapi/
  - backups/
  - node_modules/
  - scripts/
  - tests/
  - tools/
  - Docs/
  - authentication-pages/
  - template-pages/
  - "*.sql"
  - "*.py"
  - "*.sh"
  - "*.js"
  - "*.json"
  - "*.md"
  - "*.html"
  - "!index.html"
  - "!en/"
  - "!ru/"
  - "!he/"
  - Dockerfile
  - docker-compose.yml

# Include only what we need
include:
  - index.html
  - en/
  - ru/
  - he/

# GitHub Pages settings
baseurl: "/AiStudio555_Jamstack"
url: "https://sravnenie-ipotek.github.io"

# Disable Jekyll processing (we have static files)
plugins: []