version: '3.8'

services:
  strapi:
    container_name: strapi-cms
    build:
      context: .
      dockerfile: Dockerfile
    image: strapi-cms:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi_password_2024
      JWT_SECRET: ${JWT_SECRET:-3f8e5d2a9b7c1e4f6d8a2c5b9e1f4d7a}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET:-7a9c3e5f2b8d1a4e6c9f3b5d8e2a7c4f}
      APP_KEYS: ${APP_KEYS:-key1,key2,key3,key4}
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./strapi-cms/config:/opt/app/config
      - ./strapi-cms/src:/opt/app/src
      - ./strapi-cms/package.json:/opt/app/package.json
      - ./strapi-cms/yarn.lock:/opt/app/yarn.lock
      - ./strapi-cms/.env:/opt/app/.env
      - ./strapi-cms/public:/opt/app/public
    ports:
      - '1337:1337'
    networks:
      - strapi-net
    depends_on:
      - postgres

  postgres:
    container_name: strapi-postgres
    image: postgres:14-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password_2024
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - strapi-net

  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    environment:
      LT_LOAD_ONLY: "en,ru,he"
      LT_UPDATE_MODELS: "true"
    ports:
      - '5000:5000'
    networks:
      - strapi-net
    volumes:
      - libretranslate-data:/home/libretranslate/.local

volumes:
  strapi-data:
  libretranslate-data:

networks:
  strapi-net:
    driver: bridge