# Nixpacks configuration for Railway
# Ensures correct Node.js build

[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['ls -la', 'pwd']

[start]
cmd = 'node server.js'