# Railway Configuration
# IMPORTANT: Uses custom Live API server, NOT Strapi
# Due to Strapi v5 bug (all APIs return 404)

[build]
builder = "nixpacks"
buildCommand = "npm install --production"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/status"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Explicitly set the root directory
rootDirectory = "/"

# PostgreSQL will be automatically provisioned
# Railway provides DATABASE_URL environment variable