version: '3'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: strapi_v4
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=en,ru,he
      - LT_DISABLE_WEB_UI=false
    volumes:
      - libretranslate_data:/home/libretranslate/.local

volumes:
  postgres_data:
  libretranslate_data: