version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password_2024
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  libretranslate:
    image: libretranslate/libretranslate:latest
    environment:
      LT_LOAD_ONLY: "en,ru,he"
    ports:
      - '5000:5000'

volumes:
  strapi-data: